# Generated by Django 5.1.6 on 2025-03-02 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 2, 13, 23, 40, 285681)),
        ),
    ]
