# Generated by Django 5.0.6 on 2024-09-10 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('hq', '0002_hostel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
    ]
