# Generated by Django 5.0.6 on 2024-09-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hq', '0003_hostel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='additional_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='room_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
