# Generated by Django 5.0.6 on 2024-09-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hq', '0004_hostel_additional_details_hostel_room_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='price',
        ),
    ]
