# Generated by Django 5.0.6 on 2024-09-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hq', '0005_remove_hostel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='ratings',
            field=models.CharField(blank=True, max_length=244, null=True),
        ),
    ]
