# Generated by Django 5.0.6 on 2024-09-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hq', '0006_hostel_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
