# Generated by Django 5.0.6 on 2024-09-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hq', '0008_alter_hostel_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], default='available', max_length=50),
        ),
    ]
