# Generated by Django 4.2.16 on 2025-02-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=255, null=True),
        ),
    ]
