# Generated by Django 5.1.6 on 2025-03-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0002_consumer_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
