# Generated by Django 4.2.16 on 2024-11-08 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hq', '0009_alter_hostel_status'),
        ('consumers', '0002_remove_consumer_email_remove_consumer_hostel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='account_type',
        ),
        migrations.AddField(
            model_name='consumer',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hq.hostel'),
        ),
    ]
