# Generated by Django 4.2.16 on 2024-11-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0003_remove_consumer_account_type_consumer_hostel'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='room_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
