# Generated by Django 4.2.16 on 2024-11-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0004_consumer_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='room_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
